[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "solid-auth"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.10.0",
    "isort>=5.13.2",
    "mypy>=1.13.0",
]